### ISSUE TITLE
“已知bug：数据未按层级展开输出”

### ISSUE THREAD

**Issue by MichaelSun1001** [fishros/ros2bag_convert#8]
您好，请问这个bug是什么情况下才会有的？“数据未按层级展开输出”指的是到CSV中的数据有损失吗？还是有些数据只是折叠了？

**Comment by JianKangEgon** [comment]
折叠了而已，数据没有丢失。某个域的数据被合并到了同一栏了而已。最新的pr里已经修复了

**Comment by MichaelSun1001** [comment]
> 折叠了而已，数据没有丢失。某个域的数据被合并到了同一栏了而已。最新的pr里已经修复了

好的，十分感谢！！！
